/*
 * Kafka Basics Pet Project API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Order struct {

	ID string `json:"ID"`

	Products []Product `json:"Products"`

	Customer *Customer `json:"Customer"`
}
