/*
 * Kafka Basics Pet Project API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Product struct {

	ID string `json:"ID,omitempty"`

	ProductCode string `json:"ProductCode,omitempty"`

	Quantity int32 `json:"Quantity,omitempty"`
}
