/*
 * Kafka Basics Pet Project API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Address struct {

	ID string `json:"ID,omitempty"`

	Line1 string `json:"Line1,omitempty"`

	Line2 string `json:"Line2,omitempty"`

	City string `json:"City,omitempty"`

	State string `json:"State,omitempty"`

	PostalCode string `json:"PostalCode,omitempty"`
}
