openapi: '3.0.3'
info:
  title: Kafka Basics Pet Project API
  version: '1.0'
servers:
  - url: http://localhost:8080/
paths:
  /health:
    get:
      summary: 'Healthcheck'
      description: 'Responces with HTTP 200 OK'
      responses:
        '200':
          description: OK
  /order/:
    post:
      summary: 'Accepting an order'
      description: 'Saves a proper order after all the validations'
      requestBody:
        description: 'Saves the order'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      parameters: []
      responses:
        '200':
          description: OK
components:
  schemas:
    Order:
      type: object
      required: [ID, Products, Customer]
      properties:
        ID:
          type: string
          format: uuid
          example: aca4d335-a2af-43cd-910f-585e15e77c5b
        Products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        Customer:
          $ref: '#/components/schemas/Customer'
    Customer:
      type: object
      required: [ID, FirstName, EmailAddress, ShippingAddress]
      properties:
        ID:
          type: string
          format: uuid
          example: ec721712-b61b-40da-8bb6-3ce8c9a5904c
        FirstName:
          type: string
          example: John
        LastName:
          type: string
          example: Doe
        EmailAddress:
          type: string
          format: email
          example: john.doe@email.com
        ShippingAddress:
          $ref: '#/components/schemas/Address'
    Address:
      type: object
      required: [ID, Line1, City, State, PostalCode]
      properties:
        ID:
          type: string
          format: uuid
          example: ca448aff-c2fa-4328-a908-ad35eff8bacc
        Line1:
          type: string
        Line2:
          type: string
        City:
          type: string
        State:
          type: string
        PostalCode:
          type: string
    Product:
      type: object
      properties:
        ID:
          type: string
          format: uuid
          example: 1c83f686-322d-4c49-9c29-66703368d0a6
        ProductCode:
          type: string
          example: LT1234-XY
        Quantity:
          type: integer
          minimum: 1
          maximum: 100
          example: 1
